- id: '1773080312225'
  alias: TS004F Zigbee Button (ZHA)
  description: ''
  use_blueprint:
    path: patpac9/Lidl_Smart_Button_Easy_Custom_Actions.yaml
    input:
      controller: Bürobutton
      Button_single_click:
      - action: light.toggle
        metadata: {}
        data:
          brightness_pct: 100
        target:
          device_id: 38e3490a8a4e24195eea71675712ea9b
      Button_double_click:
      - action: light.toggle
        metadata: {}
        target:
          entity_id: light.schlaflicht
        data:
          brightness_pct: 100
- id: '1773096371572'
  alias: Bett onoff
  description: ''
  use_blueprint:
    path: patpac9/Lidl_Smart_Button_Easy_Custom_Actions.yaml
    input:
      controller: Bettbutton
      Button_single_click:
      - action: light.toggle
        metadata: {}
        data:
          brightness_pct: 100
        target:
          entity_id: light.schlaflicht
      Button_double_click: []
- id: '1773529423408'
  alias: licht an test2
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.motionsniffer_occupancy
      light_target:
        entity_id: light.pclampe
      no_motion_wait: 600
- id: '1773558849770'
  alias: motion-more
  description: ''
  use_blueprint:
    path: WizBangCrash/occupancy-response-sml001.yaml
    input:
      occupancy_entity: binary_sensor.motionsniffer_occupancy
      ieee_id: '0x001788010916738d'
      illuminance_entity: sensor.motionsniffer_illuminance
      luminance_value: 7
      light_entity: light.pclampe
      daytime_brightness: 75
